import type { CaseSession } from './types.js';
import { Action, DEFAULTS } from './types.js';

/**
 * Build the CLAUDE.md context string from a CaseSession.
 *
 * @param session - The active CaseSession
 * @param action - The decided action
 * @param caseData - Optional artifact/case data loaded from SQLite
 * @returns CLAUDE.md content as a string
 */
export function buildContext(session: CaseSession, action: Action, caseData?: CaseContextData): string {
  switch (action) {
    case Action.NewTurn:
      return buildFreshClaudeMd(session, caseData);
    case Action.Continue:
      return buildClaudeMdWithHistory(session, caseData);
    case Action.CompressThenContinue:
      return buildClaudeMdCompressed(session, caseData);
  }
}

/**
 * Artifact and case metadata loaded from SQLite to inject into context.
 */
export interface CaseContextData {
  title?: string;
  contentBody?: string;
  sourceUrl?: string;
  frontmatterContext?: string;
  instructionSummary?: string;
}

/**
 * Helper: build the base CLAUDE.md preamble shared by all modes.
 */
function buildPreamble(session: CaseSession): string[] {
  const lines: string[] = [];

  lines.push('# CLAUDE.md — Auto-generated by PKWS Agent Runtime');
  lines.push('');
  lines.push('## PKWS Case Context');
  lines.push('');
  lines.push('### Case ID');
  lines.push(session.caseId);
  lines.push('');

  if (session.caseInstructions) {
    lines.push('### Case Instructions');
    lines.push(session.caseInstructions);
    lines.push('');
  }

  if (session.workspaceRules.length > 0) {
    lines.push('### Workspace Rules');
    for (const rule of session.workspaceRules) {
      lines.push(`- **${rule.title}**: ${rule.content}`);
    }
    lines.push('');
  }

  if (session.systemPrompt) {
    lines.push('### System Directives');
    lines.push(session.systemPrompt);
    lines.push('');
  }

  return lines;
}

/**
 * Inject case content data into a preamble.
 */
function appendCaseData(lines: string[], data?: CaseContextData): void {
  if (!data) return;

  if (data.title || data.contentBody) {
    lines.push('### Case Content');
    lines.push('');
  }

  if (data.title) {
    lines.push(`**Title:** ${data.title}`);
    lines.push('');
  }

  if (data.sourceUrl) {
    lines.push(`**Source URL:** ${data.sourceUrl}`);
    lines.push('');
  }

  if (data.frontmatterContext) {
    lines.push('**Frontmatter:**');
    lines.push('```json');
    lines.push(data.frontmatterContext);
    lines.push('```');
    lines.push('');
  }

  if (data.contentBody) {
    // Truncate very long content to avoid exceeding CLI context limits
    const maxContentLength = 12_000;
    const body = data.contentBody.length > maxContentLength
      ? data.contentBody.slice(0, maxContentLength) + `\n\n... (truncated, ${data.contentBody.length - maxContentLength} more chars)`
      : data.contentBody;
    lines.push('**Content Body:**');
    lines.push('');
    lines.push(body);
    lines.push('');
  }
}

/**
 * Action.NewTurn: Build a fresh CLAUDE.md from SQLite-loaded session data.
 * This is the first turn or a full context rebuild after eviction recovery.
 */
function buildFreshClaudeMd(session: CaseSession, caseData?: CaseContextData): string {
  const lines = buildPreamble(session);
  appendCaseData(lines, caseData);

  if (session.messages.length > 0) {
    lines.push('### Conversation History');
    lines.push('');
    for (const msg of session.messages) {
      const label = msg.role === 'user' ? 'Human' : msg.role === 'assistant' ? 'Assistant' : 'System';
      lines.push(`${label}: ${msg.content}`);
      lines.push('');
    }

    lines.push('### Current Task');
    lines.push('Continue the work from the conversation above. Respond to the most recent Human message.');
    lines.push('');
  } else {
    lines.push('### Current Task');
    lines.push('Analyze the case content and generate a proposal. Follow the Case Instructions and Workspace Rules.');
    lines.push('');
  }

  lines.push('### Output Requirements');
  lines.push('1. Output your analysis as a structured proposal.');
  lines.push('2. If you need user input, clearly state what you need.');
  lines.push('3. Use markdown formatting.');
  lines.push('');

  return lines.join('\n');
}

/**
 * Action.Continue: Append the latest user input to existing messages.
 * This is the common case — conversation is already in memory.
 */
function buildClaudeMdWithHistory(session: CaseSession, caseData?: CaseContextData): string {
  const lines = buildPreamble(session);
  appendCaseData(lines, caseData);

  lines.push('### Conversation History');
  lines.push('Below is the ongoing conversation. Continue from the most recent message.');
  lines.push('');

  for (const msg of session.messages) {
    const label = msg.role === 'user' ? 'Human' : msg.role === 'assistant' ? 'Assistant' : 'System';
    lines.push(`${label}: ${msg.content}`);
    lines.push('');
  }

  lines.push('### Output Requirements');
  lines.push('1. Respond to the most recent Human message.');
  lines.push('2. If you need user input, clearly state what you need.');
  lines.push('3. Use markdown formatting.');
  lines.push('');

  return lines.join('\n');
}

/**
 * Action.CompressThenContinue: Compact old messages into a summary,
 * keep the most recent N messages, then continue.
 */
function buildClaudeMdCompressed(session: CaseSession, caseData?: CaseContextData): string {
  const lines = buildPreamble(session);
  appendCaseData(lines, caseData);

  lines.push('### Conversation History');
  lines.push('');

  if (session.compressedSummary) {
    lines.push('#### Earlier Conversation (compressed)');
    lines.push(session.compressedSummary);
    lines.push('');
  }

  // Show recent messages
  const keepCount = DEFAULTS.contextKeepRecentCount;
  const recentMessages = session.messages.slice(-keepCount);

  lines.push(`#### Recent Messages (last ${recentMessages.length})`);
  lines.push('');
  for (const msg of recentMessages) {
    const label = msg.role === 'user' ? 'Human' : msg.role === 'assistant' ? 'Assistant' : 'System';
    lines.push(`${label}: ${msg.content}`);
    lines.push('');
  }

  lines.push('### Output Requirements');
  lines.push('1. Respond to the most recent Human message.');
  lines.push('2. Reference the compressed earlier conversation if needed.');
  lines.push('3. If you need user input, clearly state what you need.');
  lines.push('4. Use markdown formatting.');
  lines.push('');

  return lines.join('\n');
}

/**
 * Estimate token count of a string (rough: ~4 chars per token).
 */
export function estimateTokens(text: string): number {
  return Math.ceil(text.length / 4);
}

/**
 * Perform compression on a session: fold old messages into a summary,
 * keep only the most recent N messages.
 * Mutates the session in place.
 */
export function compressSession(session: CaseSession): void {
  const keepRecent = DEFAULTS.contextKeepRecentCount;
  const totalMessages = session.messages.length;

  if (totalMessages <= keepRecent) return;

  const oldMessages = session.messages.slice(0, totalMessages - keepRecent);
  const summary = oldMessages
    .map(m => `[${m.role}]: ${m.content.slice(0, 150)}`)
    .join('; ');

  session.compressedSummary = session.compressedSummary
    ? `${session.compressedSummary}\n[Epoch ${session.compressionEpoch + 1}] ${summary}`
    : `[Epoch ${session.compressionEpoch + 1}] ${summary}`;

  session.messages = session.messages.slice(-keepRecent);
  session.compressionEpoch++;
}
