import type { CaseId } from '@pkws/shared';
import type { CliProposal, CliPatchOperation } from './output-parser.js';
import { genProposalId, genPatchManifestId, genPatchIntentId, genEventId } from '@pkws/shared/utils.js';
import type { PatchIntentAction } from '@pkws/shared';

/**
 * Write CLI output (proposal / patch operations) back to PKWS database tables.
 *
 * This bridges the Agent Runtime with the existing PKWS data model,
 * so that proposals and patches appear in the UI and follow the same
 * lifecycle as those generated via the direct LLM API path.
 */

interface WriterDb {
  select(): any;
  insert(table: any): any;
  update(table: any): any;
  run(sql: string, params: any[]): any;
}

export interface OutputWriterOptions {
  db: WriterDb;
  schema: any;
}

/**
 * Save a parsed CLI proposal to the proposals table and update the case.
 * Returns the proposal ID.
 */
export async function writeProposal(
  opts: OutputWriterOptions,
  caseId: CaseId,
  proposal: CliProposal,
  model: string,
): Promise<string> {
  const { db, schema } = opts;
  const proposalId = genProposalId();
  const now = new Date().toISOString();

  db.insert(schema.proposals).values({
    id: proposalId,
    caseId,
    model,
    title: proposal.title,
    summary: proposal.summary,
    valueJudgement: proposal.valueJudgement,
    suggestedActions: JSON.stringify(proposal.suggestedActions),
    suggestedTargetPath: proposal.suggestedTargetPath ?? null,
    reasoningSummary: proposal.reasoningSummary,
    risks: proposal.risks ? JSON.stringify(proposal.risks) : null,
    requiresPatch: proposal.requiresPatch ? 1 : 0,
    rawJson: JSON.stringify(proposal),
    createdAt: now,
  }).run();

  db.update(schema.cases).set({
    status: 'ReviewRequired',
    currentProposalId: proposalId,
    updatedAt: now,
  }).where(schema.cases.id.eq(caseId)).run();

  db.insert(schema.timelineEvents).values({
    id: genEventId(),
    caseId,
    type: 'ai_proposal_generated',
    actor: 'ai',
    summary: `Agent Runtime proposal: ${proposal.title}`,
    dataJson: JSON.stringify({ proposalId, model, source: 'agent-runtime' }),
    createdAt: now,
  }).run();

  console.log(`[OutputWriter] Saved proposal ${proposalId} for ${caseId}`);
  return proposalId;
}

/**
 * Save parsed CLI patch operations to patch_manifests table.
 * Returns the patch manifest ID.
 */
export async function writePatch(
  opts: OutputWriterOptions,
  caseId: CaseId,
  operations: CliPatchOperation[],
  patchIntentId?: string,
): Promise<string> {
  const { db, schema } = opts;
  const patchId = genPatchManifestId();
  const now = new Date().toISOString();

  // Ensure there's a patch intent
  let intentId = patchIntentId;
  if (!intentId) {
    intentId = genPatchIntentId();
    db.insert(schema.patchIntents).values({
      id: intentId,
      caseId,
      action: operations[0]?.type === 'move_file' ? 'move' : 'update_frontmatter' as PatchIntentAction,
      instruction: 'Generated by Agent Runtime',
      status: 'generated',
      createdAt: now,
      updatedAt: now,
    }).run();
  }

  // Serialize operations in PKWS PatchOperation format
  const opsJson = operations.map(op => {
    if (op.type === 'create_file') {
      return { type: 'create_file', path: op.path, content: op.content, ifExists: 'fail' };
    } else if (op.type === 'update_file') {
      return { type: 'update_file', path: op.path, newContent: op.newContent, beforeHash: '' };
    } else {
      return { type: 'move_file', fromPath: op.fromPath, toPath: op.toPath, beforeHash: '', ifTargetExists: 'fail' };
    }
  });

  db.insert(schema.patchManifests).values({
    id: patchId,
    caseId,
    patchIntentId: intentId,
    status: 'preview',
    operationsJson: JSON.stringify(opsJson),
    baseFileHashesJson: JSON.stringify({}),
    createdAt: now,
    updatedAt: now,
  }).run();

  db.update(schema.cases).set({
    status: 'PatchPreview',
    currentPatchId: patchId,
    updatedAt: now,
  }).where(schema.cases.id.eq(caseId)).run();

  db.insert(schema.timelineEvents).values({
    id: genEventId(),
    caseId,
    type: 'patch_generated',
    actor: 'ai',
    summary: `Agent Runtime patch: ${operations.length} operation(s)`,
    dataJson: JSON.stringify({ patchId, source: 'agent-runtime' }),
    createdAt: now,
  }).run();

  console.log(`[OutputWriter] Saved patch ${patchId} for ${caseId} (${operations.length} operations)`);
  return patchId;
}

/**
 * Record an AI turn event in the timeline (for audit trail).
 */
export function recordAiTurn(
  opts: OutputWriterOptions,
  caseId: CaseId,
  summary: string,
  durationMs: number,
): void {
  const { db, schema } = opts;
  const now = new Date().toISOString();

  db.insert(schema.timelineEvents).values({
    id: genEventId(),
    caseId,
    type: 'ai_proposal_started',
    actor: 'ai',
    summary: `Agent Runtime turn: ${summary} (${durationMs}ms)`,
    dataJson: JSON.stringify({ source: 'agent-runtime', durationMs }),
    createdAt: now,
  }).run();
}
